### ISSUE TITLE
Sometime get wrong stage information

### ISSUE THREAD

**Issue by GerrieWell** [Terax235/splat2api#2]
**Describe the bug**
For now, 1551520800(the day of 2019-03-02 18:00:00 in Beijing),
http://api.splatoon.terax235.me/schedules/current 
your api get output:
```json
"stage_b": {
            "name": "Skipper Pavilion",
            "id": 22,
            "image": "https://app.splatoon2.nintendo.net/images/stage/132327c819abf2bd44d0adc0f4a21aad9cc84bb2.png"
        },
        "rule": {
            "key": "turf_war",
            "name": "Turf War"
        },
        "game_mode": {
            "name": "Regular Battle",
            "key": "regular"
        },
        "stage_a": {
            "name": "Snapper Canal",
            "image": "https://app.splatoon2.nintendo.net/images/stage/8c95053b3043e163cbfaaf1ec1e5f3eb770e5e07.png",
            "id": 9
        },
        "end_time": 1551520800,
        "id": 4780952683923278000,
        "start_time": 1551513600
```
But the true stages is starfish Mainstage and the reef. 
Is it blamed to update too slow?
But why the time is right.
I can't find both stages in future hours status. It's weird.

**Comment by GerrieWell** [comment]
Dude, do u plan to fix it ?
Sometime the http://api.splatoon.terax235.me/next_update return negative time value.
I'm going to use this api in my app. So, please let me know...

**Comment by Terax235** [comment]
Ahh I see, I'll fix it as soon as possible.
